import { query } from '@/lib/db';

export type ReportingSessionStatus = 'closed' | 'open' | 'unknown' | 'other';

export type NormalizedSessionRow = {
  id: string;
  date: string | null;
  year: number | null;
  month: number | null;
  day: number | null;
  start: string | null;
  end: string | null;
  startMs: number | null;
  endMs: number | null;
  durationMin: number | null;
  hours: number | null;
  siteName: string | null;
  siteRecordId: string | null;
  clientName: string | null;
  workDescription: string | null;
  userId: number | null;
  userRecordId: string | null;
  userName: string | null;
  machineId: string | null;
  machineRecordId: string | null;
  machineName: string | null;
  status: string | null;
  statusNormalized: ReportingSessionStatus;
  autoGenerated: boolean;
  isCompleted: boolean;
};

export type SessionStatusFilter = ReportingSessionStatus | 'all';

export type FetchNormalizedSessionsParams = {
  startDate?: string | null;
  endDate?: string | null;
  year?: string | number | null;
  month?: string | number | null;
  day?: string | number | null;
  userId?: string | number | null;
  userRecordId?: string | null;
  siteName?: string | null;
  machineId?: string | number | null;
  autoGenerated?: boolean | null;
  includeOpen?: boolean;
  status?: SessionStatusFilter;
};

type SessionDbRow = {
  id: string;
  work_date: string | null;
  start_at: string | null;
  end_at: string | null;
  duration_min: number | null;
  status: string | null;
  auto_generated: boolean | null;
  decided_site_id: string | null;
  decided_site_name_snapshot: string | null;
  work_description_snapshot: string | null;
  user_id: string | null;
  machine_id: string | null;
  user_name: string | null;
  machine_name: string | null;
};

const CLOSED_STATUSES = new Set(['close', 'closed']);

function asString(value: unknown): string | null {
  if (typeof value !== 'string') return null;
  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function asNumber(value: unknown): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value !== 'string') return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function toDateParts(dateStr: string | null): { year: number | null; month: number | null; day: number | null } {
  if (!dateStr) return { year: null, month: null, day: null };
  const match = dateStr.match(/^(\d{4})-(\d{2})-(\d{2})$/);
  if (!match) return { year: null, month: null, day: null };
  return { year: Number(match[1]), month: Number(match[2]), day: Number(match[3]) };
}

export function normalizeSessionStatus(input: unknown): ReportingSessionStatus {
  if (typeof input !== 'string') return 'unknown';
  const normalized = input.trim().toLowerCase();
  if (!normalized) return 'unknown';
  if (CLOSED_STATUSES.has(normalized)) return 'closed';
  if (normalized === 'open') return 'open';
  return 'other';
}

export function mapSessionRow(row: SessionDbRow): NormalizedSessionRow {
  const date = asString(row.work_date);
  const start = asString(row.start_at);
  const end = asString(row.end_at);
  const startMsValue = start ? Date.parse(start) : Number.NaN;
  const endMsValue = end ? Date.parse(end) : Number.NaN;
  const startMs = Number.isFinite(startMsValue) ? startMsValue : null;
  const endMs = Number.isFinite(endMsValue) ? endMsValue : null;
  const computedDuration =
    startMs != null && endMs != null && endMs > startMs ? Math.round((endMs - startMs) / 60000) : null;
  const persistedDuration = asNumber(row.duration_min);
  const durationMin = persistedDuration != null && persistedDuration >= 0 ? Math.round(persistedDuration) : computedDuration;
  const status = asString(row.status);
  const statusNormalized = normalizeSessionStatus(status);
  const { year, month, day } = toDateParts(date);

  return {
    id: row.id,
    date,
    year,
    month,
    day,
    start,
    end,
    startMs,
    endMs,
    durationMin,
    hours: durationMin != null ? Math.round((durationMin / 60) * 10) / 10 : null,
    siteName: asString(row.decided_site_name_snapshot),
    siteRecordId: asString(row.decided_site_id),
    clientName: null,
    workDescription: asString(row.work_description_snapshot),
    userId: null,
    userRecordId: asString(row.user_id),
    userName: asString(row.user_name),
    machineId: asString(row.machine_id),
    machineRecordId: asString(row.machine_id),
    machineName: asString(row.machine_name),
    status,
    statusNormalized,
    autoGenerated: Boolean(row.auto_generated),
    isCompleted: statusNormalized === 'closed' && startMs != null && endMs != null && (durationMin ?? 0) > 0,
  };
}

function toNumber(value: string | number | null | undefined): number | null {
  if (typeof value === 'number' && Number.isFinite(value)) return value;
  if (typeof value !== 'string') return null;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

export async function fetchNormalizedSessions(params: FetchNormalizedSessionsParams = {}): Promise<NormalizedSessionRow[]> {
  const clauses: string[] = [];
  const values: Array<string | number | boolean> = [];
  const bind = (value: string | number | boolean): string => {
    values.push(value);
    return `$${values.length}`;
  };

  if (params.startDate) clauses.push(`s.work_date >= ${bind(params.startDate)}::date`);
  if (params.endDate) clauses.push(`s.work_date <= ${bind(params.endDate)}::date`);

  const year = toNumber(params.year);
  const month = toNumber(params.month);
  const day = toNumber(params.day);
  if (year != null) clauses.push(`EXTRACT(YEAR FROM s.work_date) = ${bind(year)}`);
  if (month != null) clauses.push(`EXTRACT(MONTH FROM s.work_date) = ${bind(month)}`);
  if (day != null) clauses.push(`EXTRACT(DAY FROM s.work_date) = ${bind(day)}`);

  const userId = toNumber(params.userId);
  if (params.userRecordId) {
    clauses.push(`s.user_id::text = ${bind(params.userRecordId)}`);
  } else if (userId != null) {
    clauses.push(`u.username = ${bind(String(userId))}`);
  }

  if (params.siteName) {
    clauses.push(`LOWER(TRIM(COALESCE(s.decided_site_name_snapshot, ''))) = LOWER(TRIM(${bind(params.siteName)}))`);
  }

  if (params.machineId) {
    clauses.push(`s.machine_id::text = ${bind(String(params.machineId))}`);
  }

  if (params.autoGenerated != null) {
    clauses.push(`COALESCE(s.auto_generated, false) = ${bind(params.autoGenerated)}`);
  }

  if (params.status && params.status !== 'all') {
    if (params.status === 'closed') {
      clauses.push(`LOWER(TRIM(COALESCE(s.status, ''))) IN ('close', 'closed')`);
    } else if (params.status === 'open') {
      clauses.push(`LOWER(TRIM(COALESCE(s.status, ''))) = 'open'`);
    } else if (params.status === 'unknown') {
      clauses.push(`TRIM(COALESCE(s.status, '')) = ''`);
    } else {
      clauses.push(`TRIM(COALESCE(s.status, '')) <> '' AND LOWER(TRIM(COALESCE(s.status, ''))) NOT IN ('open', 'close', 'closed')`);
    }
  } else if (params.includeOpen === false) {
    clauses.push(`LOWER(TRIM(COALESCE(s.status, ''))) IN ('close', 'closed')`);
  }

  const whereClause = clauses.length > 0 ? `WHERE ${clauses.join('\n        AND ')}` : '';

  const result = await query<SessionDbRow>(
    `
      SELECT
        s.id::text AS id,
        s.work_date::text AS work_date,
        s.start_at::text AS start_at,
        s.end_at::text AS end_at,
        s.duration_min,
        s.status,
        COALESCE(s.auto_generated, false) AS auto_generated,
        s.decided_site_id::text AS decided_site_id,
        s.decided_site_name_snapshot,
        s.work_description_snapshot,
        s.user_id::text AS user_id,
        s.machine_id::text AS machine_id,
        COALESCE(NULLIF(TRIM(u.name), ''), NULLIF(TRIM(u.username), '')) AS user_name,
        NULLIF(TRIM(m.name), '') AS machine_name
      FROM sessions s
      LEFT JOIN users u ON u.id = s.user_id
      LEFT JOIN machines m ON m.id = s.machine_id
      ${whereClause}
      ORDER BY s.work_date ASC, s.start_at ASC, s.id ASC
    `,
    values,
  );

  return result.rows.map(mapSessionRow);
}
