import {
  fetchNormalizedSessions,
  type FetchNormalizedSessionsParams,
  type NormalizedSessionRow,
} from '@/src/lib/sessions-reporting';

export type SessionReportRow = NormalizedSessionRow;

export type SessionReportQuery = {
  siteId?: string | null;
  siteName?: string | null;
  userId?: string | number | null;
  userName?: string | null;
  year?: string | number | null;
  month?: string | number | null;
  day?: string | number | null;
  machineId?: string | number | null;
  workDescription?: string | null;
  autoGenerated?: boolean | null;
};

function normalizeText(value: string | null | undefined): string | null {
  return value ? value.trim().toLocaleLowerCase('ja') : null;
}

function matchesQuery(row: SessionReportRow, q?: SessionReportQuery): boolean {
  if (!q) return true;
  if (q.siteId && row.siteRecordId !== q.siteId) return false;
  if (q.userName) {
    const e = normalizeText(q.userName);
    const a = normalizeText(row.userName);
    if (e && a && e !== a) return false;
  }
  if (q.workDescription) {
    const e = normalizeText(q.workDescription);
    const a = normalizeText(row.workDescription);
    if (e && a && e !== a) return false;
  }
  return true;
}

export async function fetchSessionReportRows(queryParams?: SessionReportQuery): Promise<SessionReportRow[]> {
  const params: FetchNormalizedSessionsParams = {
    year: queryParams?.year,
    month: queryParams?.month,
    day: queryParams?.day,
    userId: queryParams?.userId,
    siteName: queryParams?.siteName,
    machineId: queryParams?.machineId,
    autoGenerated: queryParams?.autoGenerated,
    includeOpen: true,
  };

  const rows = await fetchNormalizedSessions(params);
  return rows.filter((row) => row.date !== null).filter((row) => matchesQuery(row, queryParams));
}
