import { test } from 'node:test';
import assert from 'node:assert';

import { createSessionMaintenanceService } from '@/lib/services/sessions';

type LogRecord = {
  id: string;
  userId: string;
  machineId: string | null;
  decidedSiteId: string | null;
  decidedSiteNameSnapshot: string | null;
  workDescriptionSnapshot: string | null;
  workDate: string;
  stampedAtIso: string;
  stampType: 'IN' | 'OUT';
  autoGenerated: boolean;
};

function createRepo(initialLogs: Record<string, LogRecord>) {
  const openSessions: Array<{ id: string; userId: string; startAtIso: string }> = [];
  const inserted: string[] = [];
  const closed: Array<{ sessionId: string; outLogId: string; durationMin: number; autoGenerated: boolean }> = [];
  const forcedClosed: Array<{ workDate: string; forcedEndAtJstTime: string }> = [];

  return {
    state: { openSessions, inserted, closed, forcedClosed },
    repo: {
      async getLogById(logId: string) {
        return initialLogs[logId] ?? null;
      },
      async findLatestOpenSessionByUser(userId: string) {
        const latest = openSessions
          .filter((row) => row.userId === userId)
          .sort((a, b) => Date.parse(b.startAtIso) - Date.parse(a.startAtIso))[0];
        return latest ? { id: latest.id, startAtIso: latest.startAtIso } : null;
      },
      async insertOpenSession(log: LogRecord) {
        if (inserted.includes(log.id)) return;
        inserted.push(log.id);
        openSessions.push({ id: `sess-${log.id}`, userId: log.userId, startAtIso: log.stampedAtIso });
      },
      async closeOpenSession(params: {
        sessionId: string;
        outLogId: string;
        endAtIso: string;
        durationMin: number;
        autoGenerated: boolean;
      }) {
        const idx = openSessions.findIndex((row) => row.id === params.sessionId);
        if (idx === -1) return false;
        openSessions.splice(idx, 1);
        closed.push({
          sessionId: params.sessionId,
          outLogId: params.outLogId,
          durationMin: params.durationMin,
          autoGenerated: params.autoGenerated,
        });
        return true;
      },
      async forceCloseOpenSessionsByWorkDate(params: { workDate: string; forcedEndAtJstTime: string }) {
        forcedClosed.push(params);
        return 0;
      },
    },
  };
}

test('IN log creates open session', async () => {
  const logIn: LogRecord = {
    id: 'log-in-1',
    userId: '11111111-1111-4111-8111-111111111111',
    machineId: '22222222-2222-4222-8222-222222222222',
    decidedSiteId: null,
    decidedSiteNameSnapshot: 'A現場',
    workDescriptionSnapshot: '積み込み',
    workDate: '2026-02-20',
    stampedAtIso: '2026-02-20T00:00:00.000Z',
    stampType: 'IN',
    autoGenerated: false,
  };
  const { repo, state } = createRepo({ [logIn.id]: logIn });
  const service = createSessionMaintenanceService({ repo, logger: console });

  await service.handleSessionAfterLogInsert(logIn.id);

  assert.strictEqual(state.openSessions.length, 1);
  assert.strictEqual(state.inserted.length, 1);
});

test('duplicate handling does not create a second open session for same IN', async () => {
  const logIn: LogRecord = {
    id: 'log-in-2',
    userId: '11111111-1111-4111-8111-111111111111',
    machineId: '22222222-2222-4222-8222-222222222222',
    decidedSiteId: null,
    decidedSiteNameSnapshot: 'A現場',
    workDescriptionSnapshot: '積み込み',
    workDate: '2026-02-20',
    stampedAtIso: '2026-02-20T00:00:00.000Z',
    stampType: 'IN',
    autoGenerated: false,
  };
  const { repo, state } = createRepo({ [logIn.id]: logIn });
  const service = createSessionMaintenanceService({ repo, logger: console });

  await service.handleSessionAfterLogInsert(logIn.id);
  await service.handleSessionAfterLogInsert(logIn.id);

  assert.strictEqual(state.openSessions.length, 1);
  assert.strictEqual(state.inserted.length, 1);
});

test('OUT log closes latest open session and computes duration', async () => {
  const userId = '11111111-1111-4111-8111-111111111111';
  const logIn: LogRecord = {
    id: 'log-in-latest',
    userId,
    machineId: '22222222-2222-4222-8222-222222222222',
    decidedSiteId: null,
    decidedSiteNameSnapshot: 'A現場',
    workDescriptionSnapshot: '積み込み',
    workDate: '2026-02-20',
    stampedAtIso: '2026-02-20T01:00:00.000Z',
    stampType: 'IN',
    autoGenerated: false,
  };
  const logOut: LogRecord = {
    ...logIn,
    id: 'log-out-1',
    stampedAtIso: '2026-02-20T02:15:00.000Z',
    stampType: 'OUT',
  };

  const { repo, state } = createRepo({
    [logIn.id]: logIn,
    [logOut.id]: logOut,
  });
  const service = createSessionMaintenanceService({ repo, logger: console });
  await service.handleSessionAfterLogInsert(logIn.id);
  await service.handleSessionAfterLogInsert(logOut.id);

  assert.strictEqual(state.closed.length, 1);
  assert.strictEqual(state.closed[0]?.sessionId, 'sess-log-in-latest');
  assert.strictEqual(state.closed[0]?.durationMin, 75);
});

test('OUT with no open session is safely ignored', async () => {
  const logOut: LogRecord = {
    id: 'log-out-2',
    userId: '11111111-1111-4111-8111-111111111111',
    machineId: '22222222-2222-4222-8222-222222222222',
    decidedSiteId: null,
    decidedSiteNameSnapshot: 'A現場',
    workDescriptionSnapshot: '積み込み',
    workDate: '2026-02-20',
    stampedAtIso: '2026-02-20T02:15:00.000Z',
    stampType: 'OUT',
    autoGenerated: false,
  };
  const { repo, state } = createRepo({ [logOut.id]: logOut });
  const service = createSessionMaintenanceService({
    repo,
    logger: {
      warn: () => {},
      error: () => {},
    },
  });

  await service.handleSessionAfterLogInsert(logOut.id);

  assert.strictEqual(state.closed.length, 0);
  assert.strictEqual(state.openSessions.length, 0);
});

test('cron auto-generated OUT also closes open session', async () => {
  const userId = '11111111-1111-4111-8111-111111111111';
  const logIn: LogRecord = {
    id: 'log-in-cron',
    userId,
    machineId: '22222222-2222-4222-8222-222222222222',
    decidedSiteId: null,
    decidedSiteNameSnapshot: 'A現場',
    workDescriptionSnapshot: '積み込み',
    workDate: '2026-02-20',
    stampedAtIso: '2026-02-20T01:00:00.000Z',
    stampType: 'IN',
    autoGenerated: false,
  };
  const logOut: LogRecord = {
    ...logIn,
    id: 'log-out-cron',
    stampType: 'OUT',
    stampedAtIso: '2026-02-20T03:00:00.000Z',
    autoGenerated: true,
  };

  const { repo, state } = createRepo({ [logIn.id]: logIn, [logOut.id]: logOut });
  const service = createSessionMaintenanceService({ repo, logger: console });

  await service.handleSessionAfterLogInsert(logIn.id);
  await service.handleSessionAfterLogInsert(logOut.id);

  assert.strictEqual(state.closed.length, 1);
  assert.strictEqual(state.closed[0]?.autoGenerated, true);
});

test('force close uses work_date and JST forced time', async () => {
  const { repo, state } = createRepo({});
  const service = createSessionMaintenanceService({ repo, logger: console });

  const closedCount = await service.forceCloseOpenSessionsByWorkDate('2026-02-20', '17:30');

  assert.strictEqual(closedCount, 0);
  assert.strictEqual(state.forcedClosed.length, 1);
  assert.deepStrictEqual(state.forcedClosed[0], {
    workDate: '2026-02-20',
    forcedEndAtJstTime: '17:30',
  });
});
