// lib/services/reports.ts
import type { ReportRow } from "@/lib/reports/pair";
import { query } from "@/lib/db";

type UserRow = {
  id: string;
  name: string | null;
  username: string | null;
};

type SessionRow = {
  id: string;
  work_date: string; // YYYY-MM-DD
  start_at: string; // timestamptz (ISO)
  end_at: string | null; // timestamptz (ISO)
  duration_min: number | null;
  status: string | null;
  decided_site_name_snapshot: string | null;
  work_description_snapshot: string | null;
  auto_generated: boolean;
};

function formatJstTime(date: Date): string {
  return new Intl.DateTimeFormat("ja-JP", {
    timeZone: "Asia/Tokyo",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(date);
}

function splitYmd(ymd: string): { year: number; month: number; day: number } {
  const [y, m, d] = ymd.split("-").map((v) => Number.parseInt(v, 10));
  return { year: y, month: m, day: d };
}

export async function getReportRowsByUserName(
  userNameOrUsername: string,
  sort?: "year" | "month" | "day" | "siteName",
  order: "asc" | "desc" = "asc"
): Promise<ReportRow[]> {
  const key = (userNameOrUsername ?? "").trim();
  if (!key) return [];

  // name / username のどちらで選ばれても user_id を特定できるようにする
  const ures = await query<UserRow>(
    `
      SELECT id, name, username
      FROM users
      WHERE active = true
        AND (name = $1 OR username = $1 OR email = $1)
      ORDER BY (name = $1) DESC, (username = $1) DESC
      LIMIT 2
    `,
    [key]
  );
  const user = ures.rows[0] ?? null;
  if (!user?.id) return [];

  // 対象ユーザーの sessions を取得
  const sres = await query<SessionRow>(
    `
      SELECT
        id::text as id,
        work_date::text as work_date,
        start_at::text as start_at,
        end_at::text as end_at,
        duration_min,
        status,
        decided_site_name_snapshot,
        work_description_snapshot,
        COALESCE(auto_generated, false) as auto_generated
      FROM sessions
      WHERE user_id = $1::uuid
      ORDER BY work_date ASC, start_at ASC, id ASC
    `,
    [user.id]
  );

  const rows: Array<Record<string, unknown>> = [];
  for (const session of sres.rows) {
    const start = new Date(session.start_at);
    const end = session.end_at ? new Date(session.end_at) : null;
    const { year, month, day } = splitYmd(session.work_date);
    const siteName = (session.decided_site_name_snapshot ?? "").trim() || "";
    const durationMinutes = Number.isFinite(session.duration_min)
      ? Math.max(0, Math.round(session.duration_min ?? 0))
      : 0;
    rows.push({
      recordId: `S:${session.id}`,
      year,
      month,
      day,
      siteName: siteName || null,
      startTimestampMs: start.getTime(),
      endTimestampMs: end?.getTime() ?? null,
      startJst: formatJstTime(start),
      endJst: end ? formatJstTime(end) : null,
      minutes: durationMinutes,
      durationMinutes,
      autoGenerated: Boolean(session.auto_generated),
      workDescription: (session.work_description_snapshot ?? "") || "",
      breakPolicyApplied: session.status !== 'open',
    });
  }

  // 既存型との整合は repo 側の ReportRow 定義に依存するため、安全にキャスト（必須項目は埋めている）

  const sortedRows = [...rows].sort((a, b) => {
    if (!sort) return 0;

    const left = a[sort];
    const right = b[sort];

    if (typeof left === "number" && typeof right === "number") {
      return order === "asc" ? left - right : right - left;
    }

    const leftText = String(left ?? "");
    const rightText = String(right ?? "");
    const compared = leftText.localeCompare(rightText, "ja");
    return order === "asc" ? compared : -compared;
  });

  return sortedRows as unknown as ReportRow[];
}
