// lib/services/reports.ts
import type { ReportRow } from "@/lib/reports/pair";
import { query } from "@/lib/db";

type UserRow = {
  id: string;
  name: string | null;
  username: string | null;
};

type LogRow = {
  id: string;
  stamped_at: string; // timestamptz (ISO)
  work_date: string; // YYYY-MM-DD
  decided_site_name_snapshot: string | null;
  work_description: string | null;
  stamp_type: string; // IN / OUT
  auto_generated: boolean;
};

function formatJstTime(date: Date): string {
  return new Intl.DateTimeFormat("ja-JP", {
    timeZone: "Asia/Tokyo",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(date);
}

function splitYmd(ymd: string): { year: number; month: number; day: number } {
  const [y, m, d] = ymd.split("-").map((v) => Number.parseInt(v, 10));
  return { year: y, month: m, day: d };
}

function minutesBetween(a: Date, b: Date): number {
  const ms = b.getTime() - a.getTime();
  return Math.max(0, Math.round(ms / 60000));
}

export async function getReportRowsByUserName(userNameOrUsername: string): Promise<ReportRow[]> {
  const key = (userNameOrUsername ?? "").trim();
  if (!key) return [];

  // name / username のどちらで選ばれても user_id を特定できるようにする
  const ures = await query<UserRow>(
    `
      SELECT id, name, username
      FROM users
      WHERE active = true
        AND (name = $1 OR username = $1 OR email = $1)
      ORDER BY (name = $1) DESC, (username = $1) DESC
      LIMIT 2
    `,
    [key]
  );
  const user = ures.rows[0] ?? null;
  if (!user?.id) return [];

  // 対象ユーザーの logs を取得（必要ならここで期間を絞ってもOK）
  const lres = await query<LogRow>(
    `
      SELECT
        id::text as id,
        stamped_at::text as stamped_at,
        work_date::text as work_date,
        decided_site_name_snapshot,
        work_description,
        stamp_type,
        COALESCE(auto_generated, false) as auto_generated
      FROM logs
      WHERE user_id = $1::uuid
      ORDER BY stamped_at ASC
    `,
    [user.id]
  );

  // IN/OUT を時系列でペアリング
  const rows: any[] = [];
  let openIn: LogRow | null = null;

  for (const log of lres.rows) {
    const t = (log.stamp_type ?? "").toUpperCase();

    if (t === "IN") {
      // 既に IN が開いている場合は、新しい IN を優先して上書き（不整合データへの耐性）
      openIn = log;
      continue;
    }

    if (t === "OUT") {
      if (!openIn) {
        // OUT だけ先に来た場合は捨てる（必要なら別途取り扱い）
        continue;
      }

      const start = new Date(openIn.stamped_at);
      const end = new Date(log.stamped_at);

      const siteName =
        (openIn.decided_site_name_snapshot ?? "").trim() ||
        (log.decided_site_name_snapshot ?? "").trim() ||
        "";

      const { year, month, day } = splitYmd(openIn.work_date || log.work_date);

      const workingMinutes = minutesBetween(start, end);
      // ここは簡易：8h超を overtime とする（必要なら後でルール差し替え）
      const overtimeMinutes = Math.max(0, workingMinutes - 8 * 60);

      rows.push({
        recordId: `L:${openIn.id}-${log.id}`,
        year,
        month,
        day,
        siteName: siteName || null,
        startTimestampMs: start.getTime(),
        endTimestampMs: end.getTime(),
        startJst: formatJstTime(start),
        endJst: formatJstTime(end),
        workingMinutes,
        overtimeMinutes,
        autoGenerated: Boolean(log.auto_generated),
        workDescription: (openIn.work_description ?? log.work_description ?? "") || "",
      });

      openIn = null;
      continue;
    }

    // unknown stamp_type は無視
  }

  // open の IN は未完了として 1行出す（表示したくないならここを削除）
  if (openIn) {
    const start = new Date(openIn.stamped_at);
    const { year, month, day } = splitYmd(openIn.work_date);
    const siteName = (openIn.decided_site_name_snapshot ?? "").trim() || "";

    rows.push({
      recordId: `L:${openIn.id}-OPEN`,
      year,
      month,
      day,
      siteName: siteName || null,
      startTimestampMs: start.getTime(),
      endTimestampMs: null,
      startJst: formatJstTime(start),
      endJst: null,
      workingMinutes: 0,
      overtimeMinutes: 0,
      autoGenerated: Boolean(openIn.auto_generated),
      workDescription: (openIn.work_description ?? "") || "",
    });
  }

  // 既存型との整合は repo 側の ReportRow 定義に依存するため、安全にキャスト（必須項目は埋めている）
  return rows as unknown as ReportRow[];
}
