type Logger = Pick<typeof console, 'warn' | 'error'>;

type StampType = 'IN' | 'OUT';

type SessionLog = {
  id: string;
  userId: string;
  machineId: string | null;
  decidedSiteId: string | null;
  decidedSiteNameSnapshot: string | null;
  workDescriptionSnapshot: string | null;
  workDate: string;
  stampedAtIso: string;
  stampType: StampType;
  autoGenerated: boolean;
};

type OpenSession = {
  id: string;
  startAtIso: string;
};

type SessionRepository = {
  getLogById: (logId: string) => Promise<SessionLog | null>;
  findLatestOpenSessionByUser: (userId: string) => Promise<OpenSession | null>;
  insertOpenSession: (log: SessionLog) => Promise<void>;
  closeOpenSession: (params: {
    sessionId: string;
    outLogId: string;
    endAtIso: string;
    durationMin: number;
    autoGenerated: boolean;
  }) => Promise<boolean>;
  forceCloseOpenSessionsByWorkDate: (params: {
    workDate: string;
    forcedEndAtJstTime: string;
  }) => Promise<number>;
};

function asString(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

function asBoolean(value: unknown): boolean {
  if (typeof value === 'boolean') return value;
  if (value === 'true') return true;
  return false;
}

function normalizeStampType(payload: Record<string, unknown>): StampType | null {
  const raw = (asString(payload.stamp_type) ?? asString(payload.type) ?? '').toUpperCase();
  if (raw === 'IN' || raw === 'OUT') return raw;
  return null;
}

function normalizeWorkDate(payload: Record<string, unknown>, stampedAtIso: string | null): string | null {
  const direct = asString(payload.work_date) ?? asString(payload.date);
  if (direct) return direct;
  if (!stampedAtIso) return null;
  const parsed = Date.parse(stampedAtIso);
  if (!Number.isFinite(parsed)) return null;
  const jst = new Date(parsed + 9 * 60 * 60 * 1000);
  return jst.toISOString().slice(0, 10);
}

function normalizeLog(payload: Record<string, unknown>): SessionLog | null {
  const id = asString(payload.id);
  const userId = asString(payload.user_id);
  const stampType = normalizeStampType(payload);
  const stampedAtIso = asString(payload.stamped_at) ?? asString(payload.timestamp);
  const workDate = normalizeWorkDate(payload, stampedAtIso);

  if (!id || !userId || !stampType || !stampedAtIso || !workDate) {
    return null;
  }

  return {
    id,
    userId,
    machineId: asString(payload.machine_id),
    decidedSiteId: asString(payload.decided_site_id),
    decidedSiteNameSnapshot: asString(payload.decided_site_name_snapshot),
    workDescriptionSnapshot: asString(payload.work_description) ?? asString(payload.work_description_snapshot),
    workDate,
    stampedAtIso,
    stampType,
    autoGenerated: asBoolean(payload.auto_generated) || asBoolean(payload.autoGenerated),
  };
}

const defaultRepository: SessionRepository = {
  async getLogById(logId) {
    const { query } = await import('@/lib/db');
    const result = await query<{ payload: Record<string, unknown> }>(
      `
        SELECT to_jsonb(l) AS payload
        FROM logs l
        WHERE l.id = $1::uuid
        LIMIT 1
      `,
      [logId],
    );
    const payload = result.rows[0]?.payload;
    if (!payload) return null;
    return normalizeLog(payload);
  },

  async findLatestOpenSessionByUser(userId) {
    const { query } = await import('@/lib/db');
    const result = await query<{ id: string; start_at: string }>(
      `
        SELECT id, start_at
        FROM sessions
        WHERE user_id = $1::uuid
          AND status = 'open'
        ORDER BY start_at DESC
        LIMIT 1
      `,
      [userId],
    );
    const row = result.rows[0];
    if (!row) return null;
    return {
      id: row.id,
      startAtIso: row.start_at,
    };
  },

  async insertOpenSession(log) {
    const { query } = await import('@/lib/db');
    if (!log.machineId) return;

    await query(
      `
        INSERT INTO sessions (
          unique_key,
          work_date,
          user_id,
          machine_id,
          in_log_id,
          out_log_id,
          start_at,
          end_at,
          duration_min,
          status,
          auto_generated,
          decided_site_id,
          decided_site_name_snapshot,
          work_description_snapshot
        ) VALUES (
          $1,
          $2::date,
          $3::uuid,
          $4::uuid,
          $5::uuid,
          NULL,
          $6::timestamptz,
          NULL,
          0,
          'open',
          $7,
          $8::uuid,
          $9,
          $10
        )
        ON CONFLICT (unique_key) DO NOTHING
      `,
      [
        `OPEN:${log.id}`,
        log.workDate,
        log.userId,
        log.machineId,
        log.id,
        log.stampedAtIso,
        log.autoGenerated,
        log.decidedSiteId,
        log.decidedSiteNameSnapshot,
        log.workDescriptionSnapshot,
      ],
    );
  },

  async closeOpenSession({ sessionId, outLogId, endAtIso, durationMin, autoGenerated }) {
    const { query } = await import('@/lib/db');
    const result = await query(
      `
        UPDATE sessions
        SET
          out_log_id = $2::uuid,
          end_at = $3::timestamptz,
          duration_min = $4,
          status = 'closed',
          auto_generated = sessions.auto_generated OR $5,
          updated_at = NOW()
        WHERE id = $1::uuid
          AND status = 'open'
          AND out_log_id IS NULL
      `,
      [sessionId, outLogId, endAtIso, durationMin, autoGenerated],
    );
    return (result.rowCount ?? 0) > 0;
  },

  async forceCloseOpenSessionsByWorkDate({ workDate, forcedEndAtJstTime }) {
    const { query } = await import('@/lib/db');
    const result = await query(
      `
        UPDATE sessions
        SET
          end_at = (($2::date::text || ' ' || $1::text || ':00+09')::timestamptz),
          duration_min = GREATEST(
            FLOOR(
              EXTRACT(
                EPOCH FROM ((($2::date::text || ' ' || $1::text || ':00+09')::timestamptz) - start_at)
              ) / 60
            )::int,
            0
          ),
          status = 'closed',
          auto_generated = true,
          updated_at = NOW()
        WHERE work_date = $2::date
          AND status = 'open'
      `,
      [forcedEndAtJstTime, workDate],
    );
    return result.rowCount ?? 0;
  },
};

export function createSessionMaintenanceService(params?: {
  repo?: SessionRepository;
  logger?: Logger;
}) {
  const repo = params?.repo ?? defaultRepository;
  const logger = params?.logger ?? console;

  async function openSessionFromInLog(log: SessionLog): Promise<void> {
    const existing = await repo.findLatestOpenSessionByUser(log.userId);
    if (existing) return;
    await repo.insertOpenSession(log);
  }

  async function closeSessionFromOutLog(log: SessionLog): Promise<void> {
    const open = await repo.findLatestOpenSessionByUser(log.userId);
    if (!open) {
      logger.warn({
        event: 'session-close-skipped-no-open-session',
        logId: log.id,
        userId: log.userId,
      });
      return;
    }

    const startMs = Date.parse(open.startAtIso);
    const endMs = Date.parse(log.stampedAtIso);
    if (!Number.isFinite(startMs) || !Number.isFinite(endMs)) {
      logger.warn({
        event: 'session-close-skipped-invalid-timestamp',
        logId: log.id,
        sessionId: open.id,
      });
      return;
    }

    const durationMin = Math.floor((endMs - startMs) / 60_000);
    if (durationMin < 0) {
      logger.warn({
        event: 'session-close-skipped-negative-duration',
        logId: log.id,
        sessionId: open.id,
      });
      return;
    }

    await repo.closeOpenSession({
      sessionId: open.id,
      outLogId: log.id,
      endAtIso: log.stampedAtIso,
      durationMin,
      autoGenerated: log.autoGenerated,
    });
  }

  async function handleSessionAfterLogInsert(logId: string): Promise<void> {
    if (!logId) return;

    try {
      const log = await repo.getLogById(logId);
      if (!log) return;

      if (log.stampType === 'IN') {
        await openSessionFromInLog(log);
        return;
      }

      await closeSessionFromOutLog(log);
    } catch (error) {
      logger.error({
        event: 'session-maintenance-failed',
        logId,
        error,
      });
    }
  }

  async function forceCloseOpenSessionsByWorkDate(workDate: string, forcedEndAtJstTime: string): Promise<number> {
    if (!workDate || !forcedEndAtJstTime) return 0;
    try {
      return await repo.forceCloseOpenSessionsByWorkDate({ workDate, forcedEndAtJstTime });
    } catch (error) {
      logger.error({
        event: 'session-force-close-failed',
        workDate,
        forcedEndAtJstTime,
        error,
      });
      return 0;
    }
  }

  return {
    handleSessionAfterLogInsert,
    openSessionFromInLog,
    closeSessionFromOutLog,
    forceCloseOpenSessionsByWorkDate,
  };
}

const defaultService = createSessionMaintenanceService();

export const handleSessionAfterLogInsert = defaultService.handleSessionAfterLogInsert;
export const forceCloseOpenSessionsByWorkDate = defaultService.forceCloseOpenSessionsByWorkDate;
