import assert from 'node:assert/strict';
import test from 'node:test';

import { mapSessionRow, normalizeSessionStatus } from '@/src/lib/sessions-reporting';

test('normalizeSessionStatus maps canonical reporting statuses', () => {
  assert.equal(normalizeSessionStatus('closed'), 'closed');
  assert.equal(normalizeSessionStatus('close'), 'closed');
  assert.equal(normalizeSessionStatus('open'), 'open');
  assert.equal(normalizeSessionStatus(''), 'unknown');
  assert.equal(normalizeSessionStatus(null), 'unknown');
  assert.equal(normalizeSessionStatus('in_progress'), 'other');
});

test('mapSessionRow trusts duration_min and trims optional snapshots', () => {
  const row = mapSessionRow({
    id: 's-1',
    work_date: '2026-03-01',
    start_at: '2026-03-01T09:00:00+09:00',
    end_at: '2026-03-01T18:00:00+09:00',
    duration_min: 510,
    status: 'closed',
    auto_generated: false,
    decided_site_id: 'site-1',
    decided_site_name_snapshot: ' A現場 ',
    work_description_snapshot: ' 作業A ',
    user_id: 'user-1',
    machine_id: 'machine-1',
    user_name: ' 山田 ',
    user_code: '101',
    machine_name: ' M-01 ',
  });

  assert.equal(row.durationMin, 510);
  assert.equal(row.isCompleted, true);
  assert.equal(row.siteName, 'A現場');
  assert.equal(row.workDescription, '作業A');
  assert.equal(row.userName, '山田');
  assert.equal(row.machineName, 'M-01');
  assert.equal(row.userId, 101);
});

test('mapSessionRow falls back to computed duration and keeps open sessions visible', () => {
  const row = mapSessionRow({
    id: 's-open',
    work_date: '2026-03-01',
    start_at: '2026-03-01T09:00:00+09:00',
    end_at: '2026-03-01T10:15:00+09:00',
    duration_min: null,
    status: 'open',
    auto_generated: true,
    decided_site_id: null,
    decided_site_name_snapshot: '   ',
    work_description_snapshot: '',
    user_id: 'user-1',
    machine_id: null,
    user_name: null,
    user_code: null,
    machine_name: null,
  });

  assert.equal(row.durationMin, 75);
  assert.equal(row.statusNormalized, 'open');
  assert.equal(row.autoGenerated, true);
  assert.equal(row.siteName, null);
  assert.equal(row.workDescription, null);
  assert.equal(row.isCompleted, false);
});
