// app/api/calendar/day/route.ts
import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { hasDatabaseUrl } from "@/lib/server-env";
import { query } from "@/lib/db";
import { logEvent, newErrorId, toErrorMeta } from "@/lib/diagnostics";

export const runtime = "nodejs";

function parseDate(req: NextRequest): string | null {
  const { searchParams } = new URL(req.url);
  const date = searchParams.get("date");
  if (!date) return null;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return null;
  return date;
}

type DayLogRow = {
  id: string;
  stampedAt: string; // ISO
  workDate: string; // YYYY-MM-DD
  stampType: string;
  decidedSiteName: string | null;
  clientName: string | null;
  workDescription: string | null;
  autoGenerated: boolean;

  userId: string;
  userName: string | null;
  username: string | null;

  machineId: string | null;
  machineCode: number | null;
  machineName: string | null;
};

type DaySession = {
  key: string;
  date: string; // YYYY-MM-DD

  userId: string;
  userName: string | null;
  username: string | null;

  startAt: string; // ISO
  endAt: string | null; // ISO
  startJst: string; // HH:mm
  endJst: string | null; // HH:mm
  durationMin: number;
  status: "open" | "closed";

  siteName: string | null;
  clientName: string | null;
  machineCode: number | null;
  machineName: string | null;
  workDescription: string | null;

  autoGenerated: boolean;
  inLogId: string;
  outLogId: string | null;
};

type DaySummary = {
  userId: string;
  userName: string | null;
  username: string | null;
  logCount: number;
  sessionCount: number;
  sessions: DaySession[];
};

function formatJstTime(iso: string): string {
  const d = new Date(iso);
  return new Intl.DateTimeFormat("ja-JP", {
    timeZone: "Asia/Tokyo",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(d);
}

function minutesBetween(startIso: string, endIso: string): number {
  const a = new Date(startIso).getTime();
  const b = new Date(endIso).getTime();
  if (!Number.isFinite(a) || !Number.isFinite(b) || b <= a) return 0;
  return Math.max(0, Math.round((b - a) / 60000));
}

function buildSessionsForUser(date: string, logs: DayLogRow[]): DaySession[] {
  const sessions: DaySession[] = [];
  let openIn: DayLogRow | null = null;

  for (const log of logs) {
    const t = (log.stampType ?? "").toUpperCase();

    if (t === "IN") {
      openIn = log; // 既に開いていても上書き（不整合耐性）
      continue;
    }

    if (t === "OUT") {
      if (!openIn) continue;

      const startAt = openIn.stampedAt;
      const endAt = log.stampedAt;

      const siteName =
        (openIn.decidedSiteName ?? "").trim() ||
        (log.decidedSiteName ?? "").trim() ||
        null;

      const clientName =
        (openIn.clientName ?? "").trim() ||
        (log.clientName ?? "").trim() ||
        null;

      const workDescription =
        (openIn.workDescription ?? "").trim() ||
        (log.workDescription ?? "").trim() ||
        null;

      const machineCode = openIn.machineCode ?? log.machineCode ?? null;
      const machineName =
        (openIn.machineName ?? "").trim() ||
        (log.machineName ?? "").trim() ||
        null;

      sessions.push({
        key: `L:${openIn.id}-${log.id}`,
        date,

        userId: openIn.userId,
        userName: openIn.userName ?? openIn.username ?? null,
        username: openIn.username ?? null,

        startAt,
        endAt,
        startJst: formatJstTime(startAt),
        endJst: formatJstTime(endAt),
        durationMin: minutesBetween(startAt, endAt),
        status: "closed",

        siteName,
        clientName,
        machineCode,
        machineName,
        workDescription,

        autoGenerated: Boolean(log.autoGenerated),
        inLogId: openIn.id,
        outLogId: log.id,
      });

      openIn = null;
      continue;
    }

    // unknown は無視
  }

  // 開きっぱなしINも返す（UIが不要なら消してOK）
  if (openIn) {
    const startAt = openIn.stampedAt;
    sessions.push({
      key: `L:${openIn.id}-OPEN`,
      date,

      userId: openIn.userId,
      userName: openIn.userName ?? openIn.username ?? null,
      username: openIn.username ?? null,

      startAt,
      endAt: null,
      startJst: formatJstTime(startAt),
      endJst: null,
      durationMin: 0,
      status: "open",

      siteName: (openIn.decidedSiteName ?? "").trim() || null,
      clientName: (openIn.clientName ?? "").trim() || null,
      machineCode: openIn.machineCode ?? null,
      machineName: (openIn.machineName ?? "").trim() || null,
      workDescription: (openIn.workDescription ?? "").trim() || null,

      autoGenerated: Boolean(openIn.autoGenerated),
      inLogId: openIn.id,
      outLogId: null,
    });
  }

  return sessions;
}

export async function GET(req: NextRequest) {
  const errorId = newErrorId();
  const startedAt = Date.now();

  const session = await auth();
  const viewerId = session?.user?.id ?? null;

  const date = parseDate(req);

  logEvent("info", "calendar_day_request", {
    errorId,
    date,
    userId: viewerId,
    auth: viewerId ? "ok" : "missing",
  });

  if (!viewerId) {
    logEvent("warn", "calendar_day_unauthorized", { errorId });
    return NextResponse.json({ message: "unauthorized", errorId }, { status: 401 });
  }

  if (!date) {
    logEvent("warn", "calendar_day_invalid_query", { errorId });
    return NextResponse.json({ error: "INVALID_QUERY", errorId }, { status: 400 });
  }

  if (!hasDatabaseUrl()) {
    logEvent("error", "calendar_day_db_env_missing", { errorId, date });
    return NextResponse.json({ ok: false, error: "Calendar fetch failed", errorId }, { status: 500 });
  }

  try {
    const res = await query<DayLogRow>(
      `
        SELECT
          l.id::text as "id",
          l.stamped_at::text as "stampedAt",
          l.work_date::text as "workDate",
          l.stamp_type as "stampType",
          l.decided_site_name_snapshot as "decidedSiteName",
          l.client_name_snapshot as "clientName",
          l.work_description as "workDescription",
          COALESCE(l.auto_generated, false) as "autoGenerated",

          l.user_id::text as "userId",
          u.name as "userName",
          u.username as "username",

          l.machine_id::text as "machineId",
          m.machine_code as "machineCode",
          m.name as "machineName"
        FROM logs l
        LEFT JOIN users u ON u.id = l.user_id
        LEFT JOIN machines m ON m.id = l.machine_id
        WHERE l.work_date = $1::date
        ORDER BY
          CASE
            WHEN NULLIF(TRIM(COALESCE(u.username, '')), '') ~ '^[0-9]+$'
              THEN NULLIF(TRIM(COALESCE(u.username, '')), '')::bigint
            ELSE NULL
          END ASC NULLS LAST,
          COALESCE(NULLIF(TRIM(u.username), ''), '') ASC,
          COALESCE(NULLIF(TRIM(u.name), ''), '') ASC,
          l.stamped_at ASC,
          l.id ASC
      `,
      [date]
    );

    const logs = res.rows;

    // userIdごとにまとめてsession化
    const byUser = new Map<string, DayLogRow[]>();
    for (const row of logs) {
      if (!byUser.has(row.userId)) byUser.set(row.userId, []);
      byUser.get(row.userId)!.push(row);
    }

    const summaries: DaySummary[] = [];
    const allSessions: DaySession[] = [];

    for (const [userId, userLogs] of byUser.entries()) {
      const sessions = buildSessionsForUser(date, userLogs);
      summaries.push({
        userId,
        userName: userLogs[0]?.userName ?? userLogs[0]?.username ?? null,
        username: userLogs[0]?.username ?? null,
        logCount: userLogs.length,
        sessionCount: sessions.length,
        sessions,
      });
      allSessions.push(...sessions);
    }

    // ここが「未登録ユーザー」解消ポイント：
    // sessions/logs に userName/username を必ず載せて返す
    logEvent("info", "calendar_day_success", {
      errorId,
      date,
      logCount: logs.length,
      sessionCount: allSessions.length,
      durationMs: Date.now() - startedAt,
      scope: "all",
    });

    return NextResponse.json({
      date,
      scope: "all",
      viewer: {
        id: viewerId,
      },
      summaries, // UIが「ユーザーごとの概要」を期待してる場合はこちらを使える
      sessions: allSessions, // 既存UIが sessions[] を期待していてもOK
      logs, // デバッグ用にも残す
    });
  } catch (error) {
    logEvent("error", "calendar_day_error", {
      errorId,
      date,
      durationMs: Date.now() - startedAt,
      ...toErrorMeta(error),
    });
    return NextResponse.json({ ok: false, error: "Calendar fetch failed", errorId }, { status: 500 });
  }
}
