// app/api/calendar/day/route.ts
import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { hasDatabaseUrl } from "@/lib/server-env";
import { query } from "@/lib/db";
import { logEvent, newErrorId, toErrorMeta } from "@/lib/diagnostics";

export const runtime = "nodejs";

function parseDate(req: NextRequest): string | null {
  const { searchParams } = new URL(req.url);
  const date = searchParams.get("date");
  if (!date) return null;
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) return null;
  return date;
}

type DayLogRow = {
  id: string;
  stampedAt: string;
  workDate: string;
  stampType: string;
  userId: string;
};

type DaySessionRow = {
  id: string;
  workDate: string;
  userId: string;
  userName: string | null;
  username: string | null;
  machineId: string | null;
  machineCode: number | null;
  machineName: string | null;
  startAt: string;
  endAt: string | null;
  durationMin: number | null;
  status: string | null;
  decidedSiteName: string | null;
  clientName: string | null;
  workDescription: string | null;
  autoGenerated: boolean;
  inLogId: string | null;
  outLogId: string | null;
};

type DaySession = {
  key: string;
  date: string; // YYYY-MM-DD

  userId: string;
  userName: string | null;
  username: string | null;

  startAt: string; // ISO
  endAt: string | null; // ISO
  startJst: string; // HH:mm
  endJst: string | null; // HH:mm
  durationMin: number;
  status: "open" | "closed";

  siteName: string | null;
  clientName: string | null;
  machineCode: number | null;
  machineName: string | null;
  workDescription: string | null;

  autoGenerated: boolean;
  inLogId: string;
  outLogId: string | null;
};

type DaySummary = {
  userId: string;
  userName: string | null;
  username: string | null;
  logCount: number;
  sessionCount: number;
  sessions: DaySession[];
};

function formatJstTime(iso: string): string {
  const d = new Date(iso);
  return new Intl.DateTimeFormat("ja-JP", {
    timeZone: "Asia/Tokyo",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  }).format(d);
}

function normalizeSessionStatus(status: string | null, endAt: string | null): "open" | "closed" {
  const raw = (status ?? "").trim().toLowerCase();
  if (raw === "open" || raw === "active" || raw === "稼働中") return "open";
  if (raw === "closed" || raw === "close" || raw === "completed" || raw === "完了") return "closed";
  return endAt ? "closed" : "open";
}

function normalizeDurationMin(row: DaySessionRow): number {
  if (typeof row.durationMin === "number" && Number.isFinite(row.durationMin)) {
    return Math.max(0, row.durationMin);
  }
  if (!row.endAt) return 0;
  const start = Date.parse(row.startAt);
  const end = Date.parse(row.endAt);
  if (!Number.isFinite(start) || !Number.isFinite(end)) return 0;
  return Math.max(0, Math.floor((end - start) / 60_000));
}

export async function GET(req: NextRequest) {
  const errorId = newErrorId();
  const startedAt = Date.now();

  const session = await auth();
  const viewerId = session?.user?.id ?? null;

  const date = parseDate(req);

  logEvent("info", "calendar_day_request", {
    errorId,
    date,
    userId: viewerId,
    auth: viewerId ? "ok" : "missing",
  });

  if (!viewerId) {
    logEvent("warn", "calendar_day_unauthorized", { errorId });
    return NextResponse.json({ message: "unauthorized", errorId }, { status: 401 });
  }

  if (!date) {
    logEvent("warn", "calendar_day_invalid_query", { errorId });
    return NextResponse.json({ error: "INVALID_QUERY", errorId }, { status: 400 });
  }

  if (!hasDatabaseUrl()) {
    logEvent("error", "calendar_day_db_env_missing", { errorId, date });
    return NextResponse.json({ ok: false, error: "Calendar fetch failed", errorId }, { status: 500 });
  }

  try {
    const sessionRes = await query<DaySessionRow>(
      `
        SELECT
          s.id::text as "id",
          s.work_date::text as "workDate",
          s.user_id::text as "userId",
          u.name as "userName",
          u.username as "username",
          s.machine_id::text as "machineId",
          m.machine_code as "machineCode",
          m.name as "machineName",
          s.start_at::text as "startAt",
          s.end_at::text as "endAt",
          s.duration_min as "durationMin",
          s.status as "status",
          s.decided_site_name_snapshot as "decidedSiteName",
          NULL::text as "clientName",
          s.work_description_snapshot as "workDescription",
          COALESCE(s.auto_generated, false) as "autoGenerated",
          s.in_log_id::text as "inLogId",
          s.out_log_id::text as "outLogId"
        FROM sessions s
        LEFT JOIN users u ON u.id = s.user_id
        LEFT JOIN machines m ON m.id = s.machine_id
        WHERE s.work_date = $1::date
        ORDER BY
          CASE
            WHEN NULLIF(TRIM(COALESCE(u.username, '')), '') ~ '^[0-9]+$'
              THEN NULLIF(TRIM(COALESCE(u.username, '')), '')::bigint
            ELSE NULL
          END ASC NULLS LAST,
          COALESCE(NULLIF(TRIM(u.username), ''), '') ASC,
          COALESCE(NULLIF(TRIM(u.name), ''), '') ASC,
          s.start_at ASC,
          s.id ASC
      `,
      [date]
    );

    const logRes = await query<DayLogRow>(
      `
        SELECT
          l.id::text as "id",
          l.stamped_at::text as "stampedAt",
          l.work_date::text as "workDate",
          l.stamp_type as "stampType",
          l.user_id::text as "userId"
        FROM logs l
        WHERE l.work_date = $1::date
        ORDER BY l.stamped_at ASC, l.id ASC
      `,
      [date]
    );

    const sessionRows = sessionRes.rows;
    const logs = logRes.rows;

    const byUser = new Map<string, DaySession[]>();
    for (const row of sessionRows) {
      const normalizedStatus = normalizeSessionStatus(row.status, row.endAt);
      const durationMin = normalizeDurationMin(row);
      const item: DaySession = {
        key: `S:${row.id}`,
        date: row.workDate,
        userId: row.userId,
        userName: row.userName ?? row.username ?? null,
        username: row.username ?? null,
        startAt: row.startAt,
        endAt: normalizedStatus === "closed" ? row.endAt : null,
        startJst: formatJstTime(row.startAt),
        endJst: normalizedStatus === "closed" && row.endAt ? formatJstTime(row.endAt) : null,
        durationMin,
        status: normalizedStatus,
        siteName: (row.decidedSiteName ?? "").trim() || null,
        clientName: (row.clientName ?? "").trim() || null,
        machineCode: row.machineCode,
        machineName: (row.machineName ?? "").trim() || null,
        workDescription: (row.workDescription ?? "").trim() || null,
        autoGenerated: Boolean(row.autoGenerated),
        inLogId: row.inLogId ?? "",
        outLogId: row.outLogId,
      };

      if (!byUser.has(row.userId)) byUser.set(row.userId, []);
      byUser.get(row.userId)!.push(item);
    }

    const summaries: DaySummary[] = [];
    const allSessions: DaySession[] = [];

    const logsByUser = new Map<string, number>();
    for (const row of logs) {
      logsByUser.set(row.userId, (logsByUser.get(row.userId) ?? 0) + 1);
    }

    for (const [userId, sessions] of byUser.entries()) {
      summaries.push({
        userId,
        userName: sessions[0]?.userName ?? sessions[0]?.username ?? null,
        username: sessions[0]?.username ?? null,
        logCount: logsByUser.get(userId) ?? 0,
        sessionCount: sessions.length,
        sessions,
      });
      allSessions.push(...sessions);
    }

    // ここが「未登録ユーザー」解消ポイント：
    // sessions/logs に userName/username を必ず載せて返す
    logEvent("info", "calendar_day_success", {
      errorId,
      date,
      logCount: logs.length,
      sessionCount: allSessions.length,
      durationMs: Date.now() - startedAt,
      scope: "all",
    });

    return NextResponse.json({
      date,
      scope: "all",
      viewer: {
        id: viewerId,
      },
      summaries, // UIが「ユーザーごとの概要」を期待してる場合はこちらを使える
      sessions: allSessions, // 既存UIが sessions[] を期待していてもOK
      logs, // デバッグ用にも残す
    });
  } catch (error) {
    logEvent("error", "calendar_day_error", {
      errorId,
      date,
      durationMs: Date.now() - startedAt,
      ...toErrorMeta(error),
    });
    return NextResponse.json({ ok: false, error: "Calendar fetch failed", errorId }, { status: 500 });
  }
}
